Ticket 8 add comment
ElenaCKay/nc-games pull request #7
Opened 2023-04-20 07:59 UTC by ElenaCKay

I have added a sign in page which renders all users and allows the user to pick one to 'sign in'. This is then used when posting a comment as it displays the username. I have also added in a carousel feature on the main reviews page.

2023-04-20 09:17 UTC, B7Bprog requested changes
Hey Elena, there are a few points to check and correct:

- When not logged in, a user shouldn't be able to type and click to send a post. Also should be notified that they need to log in first and the post wasn't successful.
- When the connection is slow, the user should be notified that the comment is being posted or the form should be disabled to avoid multiple attempts.
- When the internet is down and the post is unsuccessful, there should be a message displayed.
- The input field should be a 'textarea' to allow multiline comments. This should be disabled when not logged in.
- Should not post when input field is empty as it currently results in an error. 

Please try to refactor your code and send us another PR with it.

2023-04-20 09:17 UTC, B7Bprog commented on src/api.js
> +    console.log(id, username, body);
Please remove this log.

2023-04-20 10:16 UTC, HeatherEver reviewed
It's looking really good but there's still just a couple of things to look at: 
- comment box needs to be a text area so the user can post a long comment and still be able to see what they've typed
- i can post an empty space " " which isn't too bad and something which can be looked at later (think about `.trim()`) 
- there's a warning in your console regarding a list element not having a key, make sure you're fixing your warning's before sending pull requests 😊

2023-04-20 10:16 UTC, HeatherEver commented on src/App.js
> +                <Route path="/reviews/:review_id" element={<Comments user={user} signedIn={signedIn}/>} />
there should not be code commented out in 'production code' - remember to keep things tidy! (line 29)

2023-04-20 10:16 UTC, HeatherEver commented on src/components/reviewItem.jsx
> +    return (
more commented out code below - remember to keep things tidy!

2023-04-20 10:16 UTC, HeatherEver commented on src/components/reviewsHeader.jsx
> +    console.log(signedIn);
remove console logs

2023-04-20 11:11 UTC, Pipe-Smoking-Rabbit requested changes
Hey Elena! It's looking fantastic, I do have some suggestions for changes on user feedback:

- When posting a comment successfully you are giving some great user feedback in the form of the text that reads "Adding your comment" 🏆  The only thing I noticed was that the entire comment section temporarily disappears, if you could make it so the comments remain on the screen but only the text input box disappears I think that would be spot on 👍 
- The other thing is that when posting in offline mode the message "Adding your comment" just hangs on the screen forever, it would be really nice to get a catch in there to render a different message informing the user of when their request has failed 

The first suggestion is more of an optional "would be nice", the second is the more important of the two. Once you've got that going hit us up with one last PR and we can get it ticked off! 😄

2023-04-20 14:37 UTC, Hard-Luck reviewed
Just a couple of things need sorting out, see my comments :) then you can merge

2023-04-20 14:37 UTC, Hard-Luck commented on src/components/addComment.jsx
> +                console.log("im in the catch");
need to remove console.logs and comments

2023-04-20 14:37 UTC, Hard-Luck commented on src/components/addComment.jsx
> +            <label>{commentFailed.toString()}</label>
<img width="542" alt="image" src="https://user-images.githubusercontent.com/72257311/233399900-2e37dce2-7e8b-47a0-85b0-4a0242435b89.png">
This is rendering on the page as "false"

2023-04-21 09:58 UTC, Poonam-raj requested changes
I have screenshotted one requirement from the ticket
<img width="527" alt="image" src="https://user-images.githubusercontent.com/61753159/233607182-bae0d560-0c1b-4ce3-8571-af9928c32365.png">

Please let the URL reflect what category I'm filtering the reviews by so I can share with a friend. Submit another PR once that's done and then i think you're good to go

2023-04-21 09:58 UTC, Poonam-raj commented on src/api.js
> +        console.log(category)
Please remove all console logs before thinking about merging this code 🙏🏾

2023-04-21 09:58 UTC, Poonam-raj commented on src/api.js
> +    //console.log(category);
Let's delete all commented out bits of code before merging

2023-04-21 10:52 UTC, Poonam-raj approved these changes
Awesome work - thanks for amending!

One thing I noticed was that when i refresh the drop-down resets despite being on the same filtered page:
![image](https://user-images.githubusercontent.com/61753159/233618125-035cad93-4b4c-497e-ae32-b68ef7622726.png)


**Brill work - feel free to merge this branch! 🎉 **

2023-04-21 10:54 UTC, merged